(lang dune 3.21)

(name ocamlatlas)

(generate_opam_files true)

(source
 (github cwkiz/ocamlatlas))

(authors "Demetrius <illegalbassmedicine@proton.me>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name ocamlatlas)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("finitegroup" "algebra" "cas" "atlasoffinitegroups")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
